### ISSUE TITLE
linkcount error

### ISSUE THREAD

**Issue by spassmo** [pttlink/Asterisk#40]
Constantly getting following error when many nodes are connected. 
`[May 13 00:56:15] WARNING[16669]: app_rpt.c:4303 linkcount: maximum number of links exceeds 32 in rpt_do_stats()!`

Need to change 
`#define MAX_STAT_LINKS 32` 
in app_rpt.c to
`#define MAX_STAT_LINKS 128`

**Comment by KG7QIN** [comment]
The maximum link count is used in a few places with the app_rpt code when dealing with updating a connected node's status.  

The function that uses this, linkcount (which threw the exception), does some checking of the reverse patch state of the link and notes if it is "DOWN".  It only cares about the first 32 links (as defined by MAX_STAT_LINKS), and if there are 33 or more then it throws this error and breaks from the loop that checks if any node has a reversepatch that is "DOWN".  It references the structure myrpt via a linked list using a while loop to parse/iterate through the data in the structure that is stored in memory.

Additionally, the main app_rpt status routine, rpt_do_stats, uses MAX_STAT_LINKS at the beginning of the function to allocate the memory for the *listoflinks pointer (char *listoflinks[MAX_STAT_LINKS];).

This is used again later within this function when checking to see if a node has keyed up or not, etc -- basically it keeps an "accurate" picture of what each connected node's status is in myrpt for use later by other parts of app_rpt -- the telemetry information that app_rpt periodically spits out on the console is one such area where this information updated by the rpt_do_stats is used..

rpt_do_stats also uses a while loop for parsing/iterating through the data stored in myrpt and will throw an exception if there are more than MAX_STAT_LINKS encountered and stops processing the status for any further connected nodes.  

Increasing this to a higher value may have an impact on the stability of app_rpt which would lead to more problems (performance, memory, etc). Testing would need to be done to ensure that this does not cause problems.  Such problems may be more noticeable on smaller systems such as the Raspberry PI.

**Comment by spassmo** [comment]
Thank you for the insight.   Apparently this change has been in place for a number of months in _the other_ distribution without any noticeable adverse affects on pi based systems.

#41

**Comment by kb4fxc** [comment]
This patch has been in place since mid 2016 in the HamVoIP.org release. Many RPi3 nodes frequently have more than 32 connections. There have been no stability issues seen or reported.

**Comment by KG7QIN** [comment]
I was thinking about this just now, and do have some more concerns as well as an idea.

Concerns:
The _other _distribution__ (as you call it) only focuses on a small subset of the possible hardware that can/is running app_rpt and connects to the AllStar network.  

While these systems, mainly Raspberry Pis and Beagle Bone Blacks, have plenty of memory and processing power to handle the potential increase in computing resources needed to manage this data structure as it grows, what about those systems on legacy x86 hardware or resource constrained embedded systems?  If you take a system with the bare minimums needed to run the underlying OS and Asterisk with app_rpt, chan_usbradio, etc and increase the amount of memory needed to handle the link reporting data structure, will the system start thrashing to disk as it has to continually hit swap and causing the system to slow down?  Or will it just segfault and die immediately (or even after a few minutes of run time)?

Considering that app_rpt has been around for a while, it is very possible that this hard limit is the result of stability testing on legacy hardware when Jim et al were creating it.

Also, with the multi-threading that happens with app_rpt and the max number of "repeaters" set to 500 in app_rpt, it doesn't seem like to far fetched of a possibility for multiple "repeater" threads to allocate all the memory used/needed at the same time leading to stability issues and other problems.

Possible solution:
Instead of hard coding the MAX_STAT_LINKS in app_rpt, a quick look of the code shows it _may_ be possible to make this a global config option in rpt.conf.  Some sanity checking would have to be done to ensure that someone doesn't try to crank this up to 65535 (or higher) and kill their system.  

rpt_links, the structure where the node link information is stored, also references a MAXLINKLIST constant which is set at 5120 (bytes).

A quick glance at the code that handles updating the links (rpt_update_links) is using the MAXLINKLIST constant a check to ensure that whatever it added to the buffer doesn't exceed this length.  Once updated, this data is copied back into the *myrpt data structure and available as the variable RPT_LINKS.  

So even with the increase of MAX_STAT_LINKS, you are still limited by the overall size that can be stored in MAXLINKLIST which is 5120 bytes.  Considering the average node length stored in this consists of 8 characters (T or M prefix, average 5 digit node number, and a comma), it may be limited to a maximum of 640 nodes -- which is lot and considering the locking and other stuff involved and would likely kill app_rpt performance and/or make it very unstable.

**Comment by KG7QIN** [comment]
An untested piece of code that would do this would look something like this.

This would go at the top of app_rpt.c:
```
#define DEFAULT_MIN_STAT_LINKS 32
#define DEFAULT_MAX_STAT_LINKS 256
```
The current `#define MAX_STAT_LINKS 32` would be replaced with:
`int MAX_STAT_LINKS = DEFAULT_MIN_STAT_LINKS;`

The line that calls a new function would be placed just before the `daq_init(cfg)` call on line 21891:
`cfg_globals_init(cfg);`

And the following code would then be inserted somewhere in app_rpt.c (preferably somewhere around line 3528 to be just before the daq_init function):


```
static void cfg_globals_init(struct ast_config *cfg)
{
	struct ast_variable *var
	int i;
	var = ast_variable_browse(cfg,"globals");
	if(!var){
		ast_log(LOG_NOTICE,"No [globals] section defined in rpt.conf!\nDefault MAX_STAT_LINKS is set to %d\n\n", DEFAULT_MIN_STAT_LINKS);
	}
	while(var){
		char *p;
		p = (char *) ast_variable_retrieve(cfg,"globals","maxlinks");
		if(p) {
			i = myatoi(p);
			if ((i < DEFAULT_MIN_STAT_LINKS) || (i > DEFAULT_MAX_STAT_LINKS)) {
				i = DEFAULT_MIN_STAT_LINKS;
				ast_log(LOG_WARNING, "maxlinks exceeds minimum or maximum allowed stat links.  Defaulting to %d\n\n", DEFAULT_MIN_STAT_LINKS); 
			}
			MAX_STAT_LINKS = i;
			ast_log(LOG_NOTICE, "MAX_STAT_LINKS = %d\n", MAX_STAT_LINKS);
		}
		
	}
}
```

You would then need to modify your rpt.conf to include the following at the top of it before any node or other definitions:

```
[globals]
maxlinks = 128
```

Some items to note:

- int MAX_STAT_LINKS _should_ really be an unsigned int instead of a signed one, since you will never have a negative value in this variable.  
- Instead of using a while loop to iterate through the [globals] section of rpt.conf, you could likely replace it with single calls to ast_variable_retrieve since each config option _**should**_ only be defined once.   A while loop will just force app_rpt to iterate through multiple declarations of this config option and use the last one it encounters.

**Comment by kb4fxc** [comment]
Hi,  How do you get out of the while(var) loop?

**Comment by KG7QIN** [comment]
Good question.  This code was hacked together in jEdit and not tested out -- it was meant as an example only.  (I used the daq_init function as my inspiration for writing this function).

To answer your question though, we would have to iterate through the linked list that is contained in var of the various items being read in from the configuration and stored in var.

You would add the following to the bottom of the while loop to do this:
`var = var->next;`

This would change the code to:
```
static void cfg_globals_init(struct ast_config *cfg)
{
	struct ast_variable *var
	int i;
	var = ast_variable_browse(cfg,"globals");
	if(!var){
		ast_log(LOG_NOTICE,"No [globals] section defined in rpt.conf!\nDefault MAX_STAT_LINKS is set to %d\n\n", DEFAULT_MIN_STAT_LINKS);
	}
	while(var){
		char *p;
		p = (char *) ast_variable_retrieve(cfg,"globals","maxlinks");
		if(p) {
			i = myatoi(p);
			if ((i < DEFAULT_MIN_STAT_LINKS) || (i > DEFAULT_MAX_STAT_LINKS)) {
				i = DEFAULT_MIN_STAT_LINKS;
				ast_log(LOG_WARNING, "maxlinks exceeds minimum or maximum allowed stat links.  Defaulting to %d\n\n", DEFAULT_MIN_STAT_LINKS); 
			}
			MAX_STAT_LINKS = i;
			ast_log(LOG_NOTICE, "MAX_STAT_LINKS = %d\n", MAX_STAT_LINKS);
		}
		var = var->next;
	}
}
```
If I get a chance at some point this week, I might add this to my local copy of app_rpt.c, see if it compiles, runs and doesn't crash. If it works, I will do a pull request against the dev branch of the this repository.

It all depends on if this would be a useful addition to app_rpt.  If it works, adding in this code could then open up adding in more global configuration options to app_rpt in the future.

**Comment by KG7QIN** [comment]
Also, I ask that if you are going to use this in the _other distro_ as a feature of app_rpt, that you credit me with it and also look at please giving back to the AllStar code repository any changes that you have done.  

We all benefit by sharing our collective efforts to make this a better program/system.

73s

**Comment by kb4fxc** [comment]
The MAX_STAT_LINKS setting is benign---at least assuming you don't go hog
wild and set this parameter to some unbelievably huge number!

As for resource usage, all memory related to this parameter is allocated
dynamically, either on the stack or heap, and only during the stats
related function calls. This impact is negligible.

BTW, I've re-written much of that code, unrolling the mutex locks as I
went. Ultimately, the rpt thread will be lock-free or at least any locks
will have very limited scope.

...MAXRPTS being set to 500 is ridiculously high! I reset that
parameter to 30, saving a lot of runtime memory!

....If you're using any applications that access stats via the AMI
(allmon2, supermon, etc.), increase the following buffer size, too. Search
for the comment...

len = 1024; /* Allocate a working buffer */

change to:

len = 10240; /* Allocate a working buffer */


...This change resolves some possible sporadic AMI related memory corruption 
concerns.


73, David KB4FXC

**Comment by KG7QIN** [comment]
Thanks.

I know we are getting off topic here on this issue, but how are you ensuring that the the threaded code you unrolled the mutexes for isn't having synchronization problems?

(It has been a while, but at one point I spent a fair amount of time with app_rpt when porting it to Asterisk 1.8.32.3.  I remember seeing a good chunk of the code using mutexes due to the threading of the main control process.)

**Comment by kb4fxc** [comment]
I'm going through a careful process-flow redesign, mostly using lock-free
data structures.

There were ALREADY synchronization problems scattered here and there in
portions of the original code; much of which seems to have been written in
the days before everybody had multi-core processors. These itty-bitty race
windows are most prevalent on slower multi-core CPUs, like the RPi2/3.
Race related crashes showed up less frequently on slow single-core
systems, like the BBB; which I guess is understandable, even if seemingly
counterintuitive.





On Tue, 29 May 2018, KG7QIN wrote:

> Thanks.
> 
> I know we are getting off topic here on this issue, but how are you 
ensuring that the the threaded code you unrolled the mutexes for isn't 
having synchronization problems?
> 
> (It has been a while, but at one point I spent a fair amount of time 
with app_rpt when porting it to Asterisk 1.8.32.3.  I remember seeing a 
good chunk of the code using mutexes due to the threading of the main 
control process.)
> 
>

**Comment by KG7QIN** [comment]
@spassmo please refer to the changes in the ASL 1.02 release.  This issue has been resolved.
